name: erad2024-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - sphinx-pythia-theme
  - arm_pyart>=1.18.7
  - cartopy
  - matplotlib
  - numpy
  - pyrad_arm
  - wradlib
  - pydda
  - zarr
  - xarray
  - xradar>=0.6.3
  - numpy<2.0
  - python<=3.11
  # this is needed for gpm-api
  - gpm-api>=0.2.15    # to update to 0.2.16 once released
  - ximage>=0.0.5
  - pycolorbar>=0.0.13 # to update to 0.0.14 once released
  - shapely>=2.0.0
  - geopandas
  - xoak
  - scikit-learn
  # this is needed for gpm-api interactive 3D viz
  # - pyvista
  # - trame
  # - trame-vuetify
  # - trame-vtk
  # this is needed for baltrad compilation
  - compilers
  - make
  - gnuconfig
  - bash
  - libaec
  - coreutils
  - autoconf
  - automake
  - tar
  - libblas=*=*netlib
  - liblapacke=*=*netlib
  # this is needed for notebooks
  - zip
  # debugging
  - sphinx>=7.4.7
  - sqlite>=3.46.0
  # mystmd
  - mystmd
  - ipykernel
  - pytest
  - pytest-xdist
  # this is needed for PyDDA performance
  - jaxopt
  - tensorflow>=2.6
  - tensorflow-probability>=0.24
  # interactive plotting
  - hvplot
  - datashader
  # needed for wradlib
  - bottleneck
  - rioxarray
  # needed for LROSE
  - metpy
