name: build-book-pullrequest

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Name of conda environment to activate'
        required: false
        default: 'cookbook-dev'
        type: string
      environment_file:
        description: 'Name of conda environment file'
        required: false
        default: 'environment.yml'
        type: string
      path_to_notebooks:
        description: 'Location of the JupyterBook source relative to repo root'
        required: false
        default: './'
        type: string
      use_cached_environment:
        description: 'Flag for whether we should attempt to retrieve a previously cached environment.'
        required: false
        default: 'true'
        type: string  # had a lot of trouble with boolean types, see https://github.com/actions/runner/issues/1483

permissions:
  contents: read

env:
  DOCKER_TAG: pr_76

jobs:
  build-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout files in repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check Changes
        run: |
          # check if binder-folder has changed
          # if changed, then a docker rebuild is needed
          echo "REBUILD=$(git diff --quiet ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} -- binder && echo unchanged || echo changed)" >> $GITHUB_ENV
      - name: remove Dockerfile
        run: |
          # if [[ ${{ env.REBUILD }} == "changed" ]]; then
          #   echo "binder-folder HAS changed - NEEDS rebuild"
          #   rm binder/Dockerfile
          # else
          #   echo "binder-folder NOT changed - NO rebuild"
          # fi
          rm binder/Dockerfile
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
          DOCKER_USERNAME: "openradar"
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: "ghcr.io"
          ADDITIONAL_TAG: ${{ env.DOCKER_TAG }}
          PUBLIC_REGISTRY_CHECK: true
          APPENDIX_FILE: "binder/appendix.txt"
          REPO2DOCKER_EXTRA_ARGS: --Repo2Docker.base_image=docker.io/library/buildpack-deps:jammy
          FORCE_REPO2DOCKER_VERSION: jupyter-repo2docker==2024.03.0

      - name: list docker images
        run: |
          docker image ls -a
      - name: Build the book
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/openradar/erad2024:latest
          options: --user root -v ${{ github.workspace }}:/work -e BASE_URL=/${{ github.event.repository.name }}/_preview/${{ github.event.pull_request.number }}
          shell: bash -l {0}
          run: |
            source /srv/conda/etc/profile.d/conda.sh
            conda activate notebook
            mamba list
            echo env
            # run notebooks
            ls -lart notebooks
            ls -lart /work/notebooks
            pytest -n auto --verbose --durations=15 --pyargs notebooks
            # build the book and copy to outside /work-folder
            myst build --ci --html
            cp -rp /home/jovyan/_build /work/.
      - name: Zip the book
        run: |
          set -x
          set -e
          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip ${{ inputs.path_to_notebooks }}/_build/html
      - name: Upload zipped book artifact
        uses: actions/upload-artifact@v4
        with:
          name: book-zip-${{github.event.number}}
          path: ./book.zip
